# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1583fd84811e23888be4f3f7d483b93ed3cae034daceec5e1d0b7d62fe2055def9fec233643d4f9e37d2e8c23f2f0a3004d922736488b38e21e7c7e7ba16a4b8

test:
  secret_key_base: 02bdcb0da6264907131d9308bdc2ad114e3d0fdb4adcb94dbadb7ede8d817b0ba07332fcf2c15da6bb23a435f5cb81ba266e0a9ae59525c66b484521d12efed8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
